// Generated by Supabase CLI / MCP from the live rostr-platform project
// (vgjmfpryobsuboukbemr, eu-west-1, "roster new").
//
// DO NOT EDIT BY HAND. To refresh after a schema change:
//
//   ./scripts/regenerate-types.sh
//
// or, with the Supabase CLI installed:
//
//   supabase gen types typescript \
//     --project-id vgjmfpryobsuboukbemr \
//     --schema public > types/supabase.ts
//
// Last regenerated: 2026-04-28

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_audit_log: {
        Row: {
          action: string
          actor_email: string | null
          actor_id: string | null
          after_value: Json | null
          before_value: Json | null
          created_at: string
          id: number
          meta: Json
          target_id: string | null
          target_type: string | null
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_id?: string | null
          after_value?: Json | null
          before_value?: Json | null
          created_at?: string
          id?: number
          meta?: Json
          target_id?: string | null
          target_type?: string | null
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_id?: string | null
          after_value?: Json | null
          before_value?: Json | null
          created_at?: string
          id?: number
          meta?: Json
          target_id?: string | null
          target_type?: string | null
        }
        Relationships: []
      }
      admin_rate_counter: {
        Row: {
          action: string
          admin_id: string
          bucket_start: string
          count: number
        }
        Insert: {
          action: string
          admin_id: string
          bucket_start: string
          count?: number
        }
        Update: {
          action?: string
          admin_id?: string
          bucket_start?: string
          count?: number
        }
        Relationships: []
      }
      artists: {
        Row: {
          available_from: string | null
          available_to: string | null
          base_fee: number | null
          blocked_dates: string[] | null
          cities_active: string[] | null
          created_at: string | null
          currency: string | null
          deleted_at: string | null
          epk_gallery: string[] | null
          epk_url: string | null
          genre: string[] | null
          id: string
          past_performances: Json | null
          press_quotes: Json | null
          profile_id: string | null
          rate_max: number | null
          rating: number | null
          rider_url: string | null
          service_tags: string[] | null
          social_links: Json | null
          stage_name: string
          status: string | null
          subgenres: string[] | null
          tech_rider: Json | null
          total_bookings: number | null
          tour_mode: boolean
          updated_at: string | null
          verified: boolean | null
        }
        Insert: {
          available_from?: string | null
          available_to?: string | null
          base_fee?: number | null
          blocked_dates?: string[] | null
          cities_active?: string[] | null
          created_at?: string | null
          currency?: string | null
          deleted_at?: string | null
          epk_gallery?: string[] | null
          epk_url?: string | null
          genre?: string[] | null
          id?: string
          past_performances?: Json | null
          press_quotes?: Json | null
          profile_id?: string | null
          rate_max?: number | null
          rating?: number | null
          rider_url?: string | null
          service_tags?: string[] | null
          social_links?: Json | null
          stage_name: string
          status?: string | null
          subgenres?: string[] | null
          tech_rider?: Json | null
          total_bookings?: number | null
          tour_mode?: boolean
          updated_at?: string | null
          verified?: boolean | null
        }
        Update: {
          available_from?: string | null
          available_to?: string | null
          base_fee?: number | null
          blocked_dates?: string[] | null
          cities_active?: string[] | null
          created_at?: string | null
          currency?: string | null
          deleted_at?: string | null
          epk_gallery?: string[] | null
          epk_url?: string | null
          genre?: string[] | null
          id?: string
          past_performances?: Json | null
          press_quotes?: Json | null
          profile_id?: string | null
          rate_max?: number | null
          rating?: number | null
          rider_url?: string | null
          service_tags?: string[] | null
          social_links?: Json | null
          stage_name?: string
          status?: string | null
          subgenres?: string[] | null
          tech_rider?: Json | null
          total_bookings?: number | null
          tour_mode?: boolean
          updated_at?: string | null
          verified?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "artists_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      booking_events: {
        Row: {
          actor_id: string | null
          booking_id: string
          created_at: string
          id: string
          kind: string
          label: string | null
          meta: Json
        }
        Insert: {
          actor_id?: string | null
          booking_id: string
          created_at?: string
          id?: string
          kind: string
          label?: string | null
          meta?: Json
        }
        Update: {
          actor_id?: string | null
          booking_id?: string
          created_at?: string
          id?: string
          kind?: string
          label?: string | null
          meta?: Json
        }
        Relationships: [
          {
            foreignKeyName: "booking_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "booking_events_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      bookings: {
        Row: {
          artist_id: string | null
          created_at: string | null
          currency: string | null
          deleted_at: string | null
          event_date: string
          event_name: string
          event_time: string | null
          event_type: string | null
          expected_attendance: number | null
          fee: number | null
          hidden_by_artist: boolean
          hidden_by_promoter: boolean
          id: string
          notes: string | null
          platform_fee: number | null
          promoter_id: string | null
          reminder_sent_at: string | null
          review_prompt_sent_at: string | null
          rider_confirmed: boolean | null
          set_duration: number | null
          status: string | null
          updated_at: string | null
          venue_id: string | null
          venue_name: string | null
        }
        Insert: {
          artist_id?: string | null
          created_at?: string | null
          currency?: string | null
          deleted_at?: string | null
          event_date: string
          event_name: string
          event_time?: string | null
          event_type?: string | null
          expected_attendance?: number | null
          fee?: number | null
          hidden_by_artist?: boolean
          hidden_by_promoter?: boolean
          id?: string
          notes?: string | null
          platform_fee?: number | null
          promoter_id?: string | null
          reminder_sent_at?: string | null
          review_prompt_sent_at?: string | null
          rider_confirmed?: boolean | null
          set_duration?: number | null
          status?: string | null
          updated_at?: string | null
          venue_id?: string | null
          venue_name?: string | null
        }
        Update: {
          artist_id?: string | null
          created_at?: string | null
          currency?: string | null
          deleted_at?: string | null
          event_date?: string
          event_name?: string
          event_time?: string | null
          event_type?: string | null
          expected_attendance?: number | null
          fee?: number | null
          hidden_by_artist?: boolean
          hidden_by_promoter?: boolean
          id?: string
          notes?: string | null
          platform_fee?: number | null
          promoter_id?: string | null
          reminder_sent_at?: string | null
          review_prompt_sent_at?: string | null
          rider_confirmed?: boolean | null
          set_duration?: number | null
          status?: string | null
          updated_at?: string | null
          venue_id?: string | null
          venue_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bookings_artist_id_fkey"
            columns: ["artist_id"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_promoter_id_fkey"
            columns: ["promoter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      client_errors: {
        Row: {
          build: string | null
          context: Json
          created_at: string
          id: string
          message: string | null
          stack: string | null
          url: string | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          build?: string | null
          context?: Json
          created_at?: string
          id?: string
          message?: string | null
          stack?: string | null
          url?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          build?: string | null
          context?: Json
          created_at?: string
          id?: string
          message?: string | null
          stack?: string | null
          url?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      contracts: {
        Row: {
          artist_signed: boolean | null
          artist_signed_at: string | null
          artist_signed_ua: string | null
          audit_log: Json | null
          booking_id: string | null
          content: string | null
          created_at: string | null
          expires_at: string | null
          id: string
          pdf_url: string | null
          promoter_signed: boolean | null
          promoter_signed_at: string | null
          promoter_signed_ua: string | null
          signed_at: string | null
          status: string | null
          title: string
        }
        Insert: {
          artist_signed?: boolean | null
          artist_signed_at?: string | null
          artist_signed_ua?: string | null
          audit_log?: Json | null
          booking_id?: string | null
          content?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string
          pdf_url?: string | null
          promoter_signed?: boolean | null
          promoter_signed_at?: string | null
          promoter_signed_ua?: string | null
          signed_at?: string | null
          status?: string | null
          title?: string
        }
        Update: {
          artist_signed?: boolean | null
          artist_signed_at?: string | null
          artist_signed_ua?: string | null
          audit_log?: Json | null
          booking_id?: string | null
          content?: string | null
          created_at?: string | null
          expires_at?: string | null
          id?: string
          pdf_url?: string | null
          promoter_signed?: boolean | null
          promoter_signed_at?: string | null
          promoter_signed_ua?: string | null
          signed_at?: string | null
          status?: string | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "contracts_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      cron_runs: {
        Row: {
          duration_ms: number | null
          error: string | null
          id: number
          job: string
          meta: Json
          ran_at: string
          status: string
        }
        Insert: {
          duration_ms?: number | null
          error?: string | null
          id?: number
          job: string
          meta?: Json
          ran_at?: string
          status: string
        }
        Update: {
          duration_ms?: number | null
          error?: string | null
          id?: number
          job?: string
          meta?: Json
          ran_at?: string
          status?: string
        }
        Relationships: []
      }
      device_tokens: {
        Row: {
          app_version: string | null
          created_at: string
          environment: string
          id: string
          last_seen_at: string
          platform: string
          token: string
          user_id: string
        }
        Insert: {
          app_version?: string | null
          created_at?: string
          environment?: string
          id?: string
          last_seen_at?: string
          platform: string
          token: string
          user_id: string
        }
        Update: {
          app_version?: string | null
          created_at?: string
          environment?: string
          id?: string
          last_seen_at?: string
          platform?: string
          token?: string
          user_id?: string
        }
        Relationships: []
      }
      email_events: {
        Row: {
          created_at: string
          from_email: string | null
          id: number
          payload: Json
          resend_id: string | null
          subject: string | null
          to_email: string | null
          type: string
        }
        Insert: {
          created_at?: string
          from_email?: string | null
          id?: number
          payload?: Json
          resend_id?: string | null
          subject?: string | null
          to_email?: string | null
          type: string
        }
        Update: {
          created_at?: string
          from_email?: string | null
          id?: number
          payload?: Json
          resend_id?: string | null
          subject?: string | null
          to_email?: string | null
          type?: string
        }
        Relationships: []
      }
      invitations: {
        Row: {
          accepted_at: string | null
          created_at: string | null
          email: string
          id: string
          invited_by: string | null
          message: string | null
          name: string | null
          role: string | null
          status: string | null
          token: string | null
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string | null
          email: string
          id?: string
          invited_by?: string | null
          message?: string | null
          name?: string | null
          role?: string | null
          status?: string | null
          token?: string | null
        }
        Update: {
          accepted_at?: string | null
          created_at?: string | null
          email?: string
          id?: string
          invited_by?: string | null
          message?: string | null
          name?: string | null
          role?: string | null
          status?: string | null
          token?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invitations_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          booking_id: string | null
          content: string
          created_at: string | null
          id: string
          read: boolean | null
          receiver_id: string | null
          sender_id: string | null
        }
        Insert: {
          booking_id?: string | null
          content: string
          created_at?: string | null
          id?: string
          read?: boolean | null
          receiver_id?: string | null
          sender_id?: string | null
        }
        Update: {
          booking_id?: string | null
          content?: string
          created_at?: string | null
          id?: string
          read?: boolean | null
          receiver_id?: string | null
          sender_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_receiver_id_fkey"
            columns: ["receiver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          booking_id: string | null
          contract_id: string | null
          created_at: string
          href: string | null
          id: string
          payment_id: string | null
          read: boolean
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body?: string | null
          booking_id?: string | null
          contract_id?: string | null
          created_at?: string
          href?: string | null
          id?: string
          payment_id?: string | null
          read?: boolean
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string | null
          booking_id?: string | null
          contract_id?: string | null
          created_at?: string
          href?: string | null
          id?: string
          payment_id?: string | null
          read?: boolean
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: []
      }
      payments: {
        Row: {
          amount: number
          artist_confirmed_at: string | null
          booking_id: string | null
          created_at: string | null
          currency: string | null
          id: string
          invoice_data: Json | null
          invoice_number: string | null
          notes: string | null
          paid_at: string | null
          payment_method: string | null
          payout_reference: string | null
          promoter_recorded_at: string | null
          provider: string | null
          status: string | null
          transaction_id: string | null
          type: string | null
        }
        Insert: {
          amount: number
          artist_confirmed_at?: string | null
          booking_id?: string | null
          created_at?: string | null
          currency?: string | null
          id?: string
          invoice_data?: Json | null
          invoice_number?: string | null
          notes?: string | null
          paid_at?: string | null
          payment_method?: string | null
          payout_reference?: string | null
          promoter_recorded_at?: string | null
          provider?: string | null
          status?: string | null
          transaction_id?: string | null
          type?: string | null
        }
        Update: {
          amount?: number
          artist_confirmed_at?: string | null
          booking_id?: string | null
          created_at?: string | null
          currency?: string | null
          id?: string
          invoice_data?: Json | null
          invoice_number?: string | null
          notes?: string | null
          paid_at?: string | null
          payment_method?: string | null
          payout_reference?: string | null
          promoter_recorded_at?: string | null
          provider?: string | null
          status?: string | null
          transaction_id?: string | null
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          city: string | null
          company: string | null
          created_at: string | null
          deleted_at: string | null
          display_name: string | null
          email: string
          id: string
          onboarding_complete: boolean | null
          onboarding_emails_sent: Json
          phone: string | null
          quick_replies: Json
          role: string
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          city?: string | null
          company?: string | null
          created_at?: string | null
          deleted_at?: string | null
          display_name?: string | null
          email: string
          id: string
          onboarding_complete?: boolean | null
          onboarding_emails_sent?: Json
          phone?: string | null
          quick_replies?: Json
          role?: string
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          city?: string | null
          company?: string | null
          created_at?: string | null
          deleted_at?: string | null
          display_name?: string | null
          email?: string
          id?: string
          onboarding_complete?: boolean | null
          onboarding_emails_sent?: Json
          phone?: string | null
          quick_replies?: Json
          role?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      reviews: {
        Row: {
          booking_id: string
          comment: string | null
          created_at: string
          hidden_at: string | null
          id: string
          rating: number
          reviewer_id: string
          target_id: string
        }
        Insert: {
          booking_id: string
          comment?: string | null
          created_at?: string
          hidden_at?: string | null
          id?: string
          rating: number
          reviewer_id: string
          target_id: string
        }
        Update: {
          booking_id?: string
          comment?: string | null
          created_at?: string
          hidden_at?: string | null
          id?: string
          rating?: number
          reviewer_id?: string
          target_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      venues: {
        Row: {
          address: string | null
          amenities: string[] | null
          capacity: number | null
          city: string
          contact_email: string | null
          contact_phone: string | null
          country: string | null
          created_at: string | null
          created_by: string | null
          id: string
          images: string[] | null
          name: string
          venue_type: string | null
        }
        Insert: {
          address?: string | null
          amenities?: string[] | null
          capacity?: number | null
          city: string
          contact_email?: string | null
          contact_phone?: string | null
          country?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          images?: string[] | null
          name: string
          venue_type?: string | null
        }
        Update: {
          address?: string | null
          amenities?: string[] | null
          capacity?: number | null
          city?: string
          contact_email?: string | null
          contact_phone?: string | null
          country?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          images?: string[] | null
          name?: string
          venue_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "venues_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _admin_rl_hit: { Args: { p_action: string }; Returns: undefined }
      _admin_rl_hit_for: {
        Args: { p_action: string; p_admin_id: string }
        Returns: undefined
      }
      _artist_user_id: { Args: { p_artist_id: string }; Returns: string }
      _current_email: { Args: never; Returns: string }
      admin_broadcast_notification: {
        Args: {
          p_body: string
          p_filter_role?: string
          p_href: string
          p_title: string
        }
        Returns: number
      }
      admin_email_stats: { Args: { p_since_hours?: number }; Returns: Json }
      admin_force_cancel_booking: {
        Args: { p_booking_id: string; p_reason?: string }
        Returns: undefined
      }
      admin_list_users: {
        Args: never
        Returns: {
          city: string
          created_at: string
          display_name: string
          email: string
          id: string
          last_sign_in_at: string
          onboarding_complete: boolean
          role: string
        }[]
      }
      admin_stats: { Args: never; Returns: Json }
      admin_undo_last_action: {
        Args: { p_target_id: string; p_target_type: string }
        Returns: Json
      }
      admin_update_user_role: {
        Args: { p_role: string; p_user_id: string }
        Returns: undefined
      }
      check_availability: {
        Args: { p_artist_id: string; p_event_date: string }
        Returns: {
          available: boolean
          reason: string
        }[]
      }
      claim_artist_profile: {
        Args: { target_artist_id: string }
        Returns: {
          available_from: string | null
          available_to: string | null
          base_fee: number | null
          blocked_dates: string[] | null
          cities_active: string[] | null
          created_at: string | null
          currency: string | null
          deleted_at: string | null
          epk_gallery: string[] | null
          epk_url: string | null
          genre: string[] | null
          id: string
          past_performances: Json | null
          press_quotes: Json | null
          profile_id: string | null
          rate_max: number | null
          rating: number | null
          rider_url: string | null
          service_tags: string[] | null
          social_links: Json | null
          stage_name: string
          status: string | null
          subgenres: string[] | null
          tech_rider: Json | null
          total_bookings: number | null
          tour_mode: boolean
          updated_at: string | null
          verified: boolean | null
        }
        SetofOptions: {
          from: "*"
          to: "artists"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_review: {
        Args: { p_booking_id: string; p_comment?: string; p_rating: number }
        Returns: string
      }
      cron_health_public: {
        Args: never
        Returns: {
          failures_24h: number
          failures_7d: number
          job: string
          last_10: Json
          last_ran_at: string
          last_status: string
          runs_24h: number
          runs_7d: number
        }[]
      }
      cron_health_summary: {
        Args: never
        Returns: {
          failures_24h: number
          failures_7d: number
          job: string
          last_10: Json
          last_error: string
          last_ran_at: string
          last_status: string
          runs_24h: number
          runs_7d: number
        }[]
      }
      cron_history_7d: {
        Args: { p_job: string }
        Returns: {
          day: string
          error_runs: number
          total_runs: number
        }[]
      }
      current_role: { Args: never; Returns: string }
      expire_stale_contracts: { Args: never; Returns: number }
      generate_invoice_number: { Args: never; Returns: string }
      is_admin: { Args: never; Returns: boolean }
      log_admin_action: {
        Args: {
          p_action: string
          p_meta?: Json
          p_target_id?: string
          p_target_type?: string
        }
        Returns: number
      }
      log_cron_run: {
        Args: {
          p_duration_ms?: number
          p_error?: string
          p_job: string
          p_meta?: Json
          p_status: string
        }
        Returns: undefined
      }
      log_impersonation_event: {
        Args: {
          p_action: string
          p_admin_email: string
          p_meta?: Json
          p_target_id?: string
          p_target_type?: string
        }
        Returns: number
      }
      review_stats_for_user: {
        Args: { p_user_id: string }
        Returns: {
          avg_rating: number
          review_count: number
        }[]
      }
      reviews_for_user: {
        Args: { p_limit?: number; p_user_id: string }
        Returns: {
          comment: string
          created_at: string
          event_date: string
          event_name: string
          id: string
          rating: number
          reviewer_name: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
